version: 0.2

phases:
  install:
    commands:
      # install terraform
      - curl -s -qL -o terraform_install.zip "https://releases.hashicorp.com/terraform/1.5.5/terraform_1.5.5_linux_amd64.zip"
      - unzip terraform_install.zip -d /usr/bin/
      - chmod +x /usr/bin/terraform
    finally:
      - terraform --version
  build:
    commands:
      - echo "Build Phase - Running Terraform Apply"
      - terraform apply -auto-approve
  # post_build:
  #   commands:
  #     - echo "Post-Build Phase - Running Cleanup"
  #     - terraform destroy -auto-approve

artifacts:
  files:
    - "**/*"
  discard-paths: yes
