version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform"
      - wget https://releases.hashicorp.com/terraform/1.7.3/terraform_1.7.3_linux_arm64.zip
      - unzip terraform_1.7.3_linux_arm64.zip
      - mv terraform /usr/local/bin/
      - export PATH=$PATH:/usr/local/bin/ # Add /usr/local/bin/ to the PATH
      - /usr/local/bin/terraform --version # Use full path
    finally:
      - terraform --version
  pre_build:
    commands:
      - echo "Pre-Build Phase - Running Terraform Init"
      - cat main.tf
      - terraform init
  build:
    commands:
      - echo "Build Phase - Running Terraform Apply"
      - terraform apply -auto-approve
      - ls -ltr
  # post_build:
  #   commands:
  #     - echo "Post-Build Phase - Running Cleanup"
  #     - terraform destroy -auto-approve

artifacts:
  files:
    - "**/*"
  discard-paths: yes
