version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform"
      - wget https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
      - unzip terraform_1.0.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version # Verify Terraform installation
  build:
    commands:
      - echo "Build Phase - Running Terraform Apply"
      - terraform apply -auto-approve
  # post_build:
  #   commands:
  #     - echo "Post-Build Phase - Running Cleanup"
  #     - terraform destroy -auto-approve

artifacts:
  files:
    - "**/*"
  discard-paths: yes
